# Generated by Django 3.1.3 on 2021-03-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
