# Generated by Django 3.1.3 on 2021-03-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20210304_1852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercie',
            new_name='Exercise',
        ),
    ]
