# Generated by Django 3.1.3 on 2021-02-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210225_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='dob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
