# Generated by Django 3.1.3 on 2021-02-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210225_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.DeleteModel(
            name='Exercie',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
