# Generated by Django 3.1.3 on 2021-03-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210226_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
