# Generated by Django 3.1.3 on 2021-03-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_user',
        ),
    ]
