# Generated by Django 3.1.3 on 2021-04-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210327_1334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
