# Generated by Django 3.1.3 on 2021-04-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_notification_notificationforbirthday_notificationforpost_notificationsforfriendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationsforfriendrequest',
            old_name='user',
            new_name='sent_by',
        ),
        migrations.RemoveField(
            model_name='notificationforpost',
            name='user',
        ),
    ]
