# Generated by Django 3.1.3 on 2021-04-07 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210319_1855'),
        ('home', '0018_auto_20210407_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsforfriendrequest',
            name='sent_by',
        ),
        migrations.AddField(
            model_name='notificationforpost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='notificationsforfriendrequest',
            name='friend_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.friendrequest'),
        ),
    ]
