# Generated by Django 3.1.3 on 2021-02-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_bmi_bmr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.DeleteModel(
            name='Exercie',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
