# Generated by Django 3.1.3 on 2021-04-29 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
